//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rations_V2.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Standart : global::System.Configuration.ApplicationSettingsBase {
        
        private static Standart defaultInstance = ((Standart)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Standart())));
        
        public static Standart Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1250")]
        public double StandartMeatActivityCs {
            get {
                return ((double)(this["StandartMeatActivityCs"]));
            }
            set {
                this["StandartMeatActivityCs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double StandartMilkActivityCs {
            get {
                return ((double)(this["StandartMilkActivityCs"]));
            }
            set {
                this["StandartMilkActivityCs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public double StandartMilkActivitySr {
            get {
                return ((double)(this["StandartMilkActivitySr"]));
            }
            set {
                this["StandartMilkActivitySr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double MeasureOfInaccuracy {
            get {
                return ((double)(this["MeasureOfInaccuracy"]));
            }
            set {
                this["MeasureOfInaccuracy"] = value;
            }
        }
    }
}
